[package]
name = "lt_delta"
version = "0.1.0"
edition = "2021"
authors = ["Florian Pircher <florian@formkunft.com>"]
description = "A type Delta<T> representing a source, a target, or both."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Formkunft/lt_delta"

[dependencies]
